- README.md
travis activated. this is also test of travis build.
> embed build status

- Dockerfile.kinetic
- aero_samples/CMakeLists.txt
- aero_startup/.templates/CMakeLists.template
- aero_startup/.templates/aero_controller_manager/AeroJointStatePublisher.cc
- aero_startup/aero_controller_manager/AeroJointStatePublisher.hh
- aero_startup/aero_hardware_interface/AeroControllerNode.cc
- aero_startup/aero_hardware_interface/AeroControllerNode.hh
- aero_startup/package.xml
- aero_std/CMakeLists.txt
- aero_std/include/aero_std/AeroMoveitInterface.hh
- aero_std/src/AeroMoveitInterface.cc
- aeroeus/aero-arm-interface.l
- aeroeus/aero-interface.l
#265 DO NOT MERGE YET
#267 が解決できておらず，未だ大量のwarnが出ます．
こちらも対応を行い，別のコミットとして更新します．
> Apply Kinetic

- aero_startup/aero_hardware_interface/AeroControllerNode.cc
- aero_startup/aero_hardware_interface/AeroControllerNode.hh
major controller update.
fix interference handling for constant mode.
adding slow down/speed up motion after command is sent.
tested for single trajectory commands on real robot.
update does not gaurantee for multiple trajectory.
> Update controller feb18

- aero_shop/typeB_lifter/urdf/virtual_lifter.urdf.xacro
- aero_shop/typeF_upperbody/urdf/aero_upper_typef.urdf.xacro
they are slower than previous ones, but the ratio of each other is more accurate.
> modified max joint velocities

- aero_description/README.md
- aero_description/scripts/create_eusmodel.sh
- aero_description/scripts/create_urdf.sh
- aero_description/setup.sh
- aero_description/typeF/robots/aero.yaml
#279 
下半身の仕様が固まっていませんが，あとで編集すれば行けるはずです．
${my_robot}/robots/の下に
aero.{urdf.xacro,yaml}がある場合それを利用してeusモデルを作ります．
逆にそのどちらかでも存在しなければ何もしないので
用意していない構成の場合にも問題はありませんでした．
> add eusmodel generator

- aero_startup/aero_move_base/launch/amcl.launch
変更の結果、localizationの結果が良くなりました。
> change odom_model_type and odom_alpha values

- aero_description/package.xml
- aero_moveit_config/package.xml
- aero_ros_controller/package.xml
- aero_samples/package.xml
- aero_sensors/package.xml
- aero_startup/package.xml
- aero_std/package.xml
https://github.com/seed-solutions/aero-ros-pkg/issues/315
> fix package.xml

- aero_description/typeF/robots/controller_settings.yaml
- aero_ros_controller/include/aero_ros_controller/RobotInterface.hh
- aero_ros_controller/src/RobotInterface.cc
- aero_std/include/aero_std/AeroRobotInterface.hh
Fix problem reported 
https://github.com/seed-solutions/aero-ros-pkg/issues/320
> configure controller settings from param

- README.md
additional notes of rosdep for beginners
> [readme] add rosdep information for beginners

- aero_description/common_urdf/gazebo.xacro
- aero_description/typeF/robots/aero.urdf.xacro
- aero_description/typeFBDSy/robots/aero.urdf.xacro
- aero_description/typeFCESy/robots/aero.urdf.xacro
- aero_gazebo/src/MimicPlugin.cpp
- aero_ros_controller/include/aero_ros_controller/RobotInterface.hh
- aero_ros_controller/src/RobotInterface.cc
https://github.com/seed-solutions/aero-ros-pkg/issues/327
> Fix for using gazebo in indigo

- aero_description/typeFCESy/moveit_config/config/AeroUpperRobot.srdf
- aero_moveit_config/.setup_assistant
- aero_moveit_config/launch/real_robot.launch
For updating files for moveit, use this command.
~~~
roslaunch moveit_setup_assistant setup_assistant.launch
~~~
new file ```real_robot.launch``` is added for real robot use.
> Fix moveit

- aero_shop/seed_hand/urdf/seed_hand.urdf.xacro
- aero_shop/trx_s/urdf/trx_s.urdf.xacro
add transmission to under actuated joint for publishing joint_state
> [aero_shop, seed_hand/trx_s] fix finger joints

- aero_std/src/AeroMoveitInterface.cc
getLifter should return a negative z value and match with setLifter.
> fix getLifter

- Dockerfile.indigo
- Dockerfile.kinetic
- aero_samples/CMakeLists.txt
- aero_samples/package.xml
- aero_samples/tests/test_ik.cc
- aero_samples/tests/test_ik.test
- aero_shop/typeC_lifter/urdf/lifter.urdf.xacro
- aero_std/src/AeroMoveitInterface.cc
This may solve #344
Test for IK is added
> fix limit of mimic joints

- aero_description/common_urdf/gazebo.xacro
- aero_description/typeF/robots/gazebo_controller_settings.yaml
- aero_description/typeFBDSy/robots/gazebo_controller_settings.yaml
- aero_description/typeFCESy/robots/aero.urdf.xacro
- aero_description/typeFCESy/robots/gazebo_controller_settings.yaml
- aero_gazebo/src/MimicPlugin.cpp
- aero_gazebo/src/MimicPlugin.h
- aero_shop/hand_yaw/urdf/hand_yaw.urdf.xacro
- aero_shop/typeF_upperbody/urdf/aero_upper_typef.urdf.xacro
use velocity feedback instead of torque feedback
> Fix gazebo settings

- aero_startup/aero_move_base/launch/amcl.launch
- aero_startup/aero_move_base/launch/static_map_navigation.launch
- aero_startup/aero_move_base/launch/wheel_with_static_map.launch
assuming that representing cost and obstacles with one map.is not possible
in case this can be done with one map, the pull request should be declined
> allow different maps for cost and path

- Dockerfile.indigo
- Dockerfile.kinetic
apt-get dist-upgrade is required
> fix Dockerfile for travis

- README.md
- aero_moveit_config/README.md
Added README.md about aero_moveit_config to use RViz Motion Planning Plugin.
This update is not complete.
> Add readme

- aero_moveit_config/README.md
This update will delete after WMD2018 finish.
> update about udev_setting for only  WMD2018

- aero_moveit_config/README.md
This update will delete after WMD2018 finish.
> Update about SSH

- aero_ros_controller/src/AeroMoveBaseRH.cc
fix publishing non-zero odometry when zero command velocity comes
> Fix odometry

- aero_description/typeF/moveit_config/config/joint_limits.yaml
- aero_description/typeFBDSy/moveit_config/config/joint_limits.yaml
- aero_description/typeFCESy/moveit_config/config/joint_limits.yaml
- aero_shop/hand_yaw/urdf/hand_yaw.urdf.xacro
- aero_shop/typeC_lifter/urdf/lifter.urdf.xacro
- aero_shop/typeF_upperbody/urdf/aero_upper_typef.urdf.xacro
If a step-out occurs within normal ranges of use, please point out. 
If nothing, I will merge this PR in two weeks.
> update velocity parameters of each joints

- aero_teleop/CMakeLists.txt
- aero_teleop/config/ps4.config.yaml
- aero_teleop/include/aero_teleop/xbox_one_teleop.hh
- aero_teleop/launch/aero_teleop2.launch
- aero_teleop/src/xbox_one_teleop.cc
- aero_teleop/src/xbox_one_teleop_node.cc
adding source code for ps4 controller since some buttons in ps3 are axes in ps4
the code name is xbox since placement of buttons and axes are the same as the xbox controller
should not need to update README since it is mostly the same as the ps3 controller
> add ps4 teleop controller

- aero_gazebo/launch/aero_gazebo.launch
- aero_startup/aero_move_base/config/DWAPlanner.yaml
- aero_startup/aero_move_base/launch/README.md
- aero_startup/aero_move_base/launch/amcl.launch
- aero_startup/aero_move_base/launch/move_base.launch
- aero_startup/aero_move_base/launch/static_map_navigation.launch
- aero_startup/aero_move_base/launch/wheel_with_static_map.launch
- Change map name, 'costmap' to 'map_localization', because 'costmap' does not understand the role of it
- Add documentation for describing map topic and file
> [aero_move_base] fix names of map topics and arguments for launch

- .travis.yml
- Dockerfile.melodic
- aero_description/common_urdf/gazebo.xacro
- aero_description/typeF/headers/Angle2Stroke.hh
- aero_description/typeF/headers/Stroke2Angle.hh
- aero_description/typeFBDSy/headers/Angle2Stroke.hh
- aero_description/typeFBDSy/headers/Stroke2Angle.hh
- aero_description/typeFCESy/headers/Angle2Stroke.hh
- aero_description/typeFCESy/headers/Stroke2Angle.hh
- aero_gazebo/CMakeLists.txt
- aero_gazebo/src/MimicPlugin.cpp
- aero_gazebo/src/MimicPlugin.h
- aero_gazebo/src/gazebo_ros_planar_move.cpp
- aero_gazebo/src/gazebo_ros_planar_move.h
- aero_samples/CMakeLists.txt
- aero_shop/typeE_wheel/urdf/wheels.urdf.xacro
- aero_std/CMakeLists.txt
- aero_std/include/aero_std/IKSettings.hh
This is a temporary change for gazebo.
Change of plugins should be added to the original plugin.
Then, we have to evaluate this plugin works well.
> Change plugin for moving base in gazebo

- aero_startup/aero_move_base/launch/wheel_bringup.launch
Just in case urg_node down for some reason, add respawn option.
> add respawn option for urg_node

- README.md
Fix the wrong operation for teleop.
> fix README for teleop

- aero_gazebo/src/gazebo_ros_planar_move.cpp
- aero_gazebo/src/gazebo_ros_planar_move.h
resolve https://github.com/seed-solutions/aero-ros-pkg/issues/401
> [aero_gazebo] add velocityDeadZone for fixing base while not receiving cmd_vel

- aero_startup/aero_move_base/launch/amcl.launch
- aero_startup/aero_move_base/launch/wheel_with_making_map.launch
I added arg value in launch file to allow easy overwriting by another launch file.
> add args to launch files
